### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by sumanthrao1997** [juliangaal/warpsense#1]
Thank you for the work. 
 
The repository doesn't compile,
Initially I got an error saying IKDTree.h not found.
I disable tests in CmakeLists and it was gone .

But after that I have a strange issue

/usr/bin/ld: CMakeFiles/featsense.dir/src/featsense/mapping.cpp.o: in function `apply_registration(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >&, boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >&, float)':
mapping.cpp:(.text._Z18apply_registrationRN5boost10shared_ptrIN3pcl10PointCloudINS1_9PointXYZIEEEEES6_f[_Z18apply_registrationRN5boost10shared_ptrIN3pcl10PointCloudINS1_9PointXYZIEEEEES6_f]+0xcc): undefined reference to `fast_gicp::FastVGICPCuda<pcl::PointXYZI, pcl::PointXYZI>::setInputTarget(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'

Could you please help, I see that fastgicp is included in catkin_libraries in the CMakeLists but still dosen't work

**Comment by juliangaal** [comment]
Probably a good idea to disable building tests by default.

Please tell me more about your build environment.

* Did you compile fast_gicp with CUDA support?
* OS?
* ROS Version?

**Comment by sumanthrao1997** [comment]
Thank you for the quick reply.

I have fastgicp with cuda as well.

I am using ros noetic on ubuntu 20.04. 
I have cuda 11.08. as and gcc 9.4.0.

**Comment by juliangaal** [comment]
which version of fast_gicp did you use?

**Comment by sumanthrao1997** [comment]
I used the master branch

**Comment by juliangaal** [comment]
Ok, I made the mistake of not adding the correct fast_gicp version as a submodule as well. Could you try to build the repo with a different version of fast_gicp?

For example, commit `aff82ee0778178b8942e2d4d31855c0d8421ac3b` is from July 22. This work was completed in Nov/22. Please try an older commit like this one:

```
cd fast_gicp
git checkout aff82ee0778178b8942e2d4d31855c0d8421ac3b
<compile with CUDA enabled>
```
Please start from a clean workspace to minimize the chance other issues arising.

UPDATE: test compilation is now off by default

**Comment by amock** [comment]
For me it was working with fast_gicp commit "ee1fdbae7dd86284b52a06141358c89982d67850" from Feb 2023:

```console
cd fast_gicp
git checkout ee1fdbae7dd86284b52a06141358c89982d67850
<compile with CUDA enabled>
```

@sumanthrao1997 : It would be interesting to know from which version on it starts to fail compiling.

Greetings
Alex

**Comment by sumanthrao1997** [comment]
Unfortunately I was unable to get it running with your suggestion, I have the same error as below. 

could you please let me know the PCL version you are using.

 /usr/bin/ld: warning: libpcl_filters.so.1.13, needed by /usr/local/lib/libpcl_segmentation.so, may conflict with libpcl_filters.so.1.10
/usr/bin/ld: CMakeFiles/featsense.dir/src/featsense/mapping.cpp.o: in function `apply_registration(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >&, boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >&, float)':
mapping.cpp:(.text._Z18apply_registrationRN5boost10shared_ptrIN3pcl10PointCloudINS1_9PointXYZIEEEEES6_f[_Z18apply_registrationRN5boost10shared_ptrIN3pcl10PointCloudINS1_9PointXYZIEEEEES6_f]+0xcc): undefined reference to `fast_gicp::FastVGICPCuda<pcl::PointXYZI, pcl::PointXYZI>::setInputTarget(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
/usr/bin/ld: mapping.cpp:(.text._Z18apply_registrationRN5boost10shared_ptrIN3pcl10PointCloudINS1_9PointXYZIEEEEES6_f[_Z18apply_registrationRN5boost10shared_ptrIN3pcl10PointCloudINS1_9PointXYZIEEEEES6_f]+0x107): undefined reference to `fast_gicp::FastVGICPCuda<pcl::PointXYZI, pcl::PointXYZI>::setInputSource(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/featsense.dir/build.make:666: /home/s/fnt_ws/devel/.private/warpsense/lib/warpsense/featsense] Error 1
make[1]: *** [CMakeFiles/Makefile2:2985: CMakeFiles/featsense.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by amock** [comment]
Just now, I redid the steps we explained and at least for my system it is compiling. With the fast_gicp commit I wrote before.

Now we have to figure out what's different to your system. At first, your compiler says your two PCL versions "may" conflict. I have pcl from standard sources installed at /lib/x86_64-linux-gnu/. You have a second PCL installed at /usr/local/lib/. In general, it should not be a problem to have two versions of a software installed, but try to remove the "/usr/local/lib" one. I assume you installed it by source using cmake somewhere. If you are lucky you can just call make uninstall in the build folder of your PCL source directory.

But my feeling says the main reason for failure lies in fast_gicp. Are you sure you are at commit "ee1fdbae7dd86284b52a06141358c89982d67850" there? Have you tried removing the "build" "devel" and "log" folder before recompiling?

My system:
- Ubuntu 20.04.6 LTS
- NVIDIA GeForce RTX 2070 SUPER + Driver 470.223.02 + CUDA 11.4
- AMD Ryzen 7 3700x
- warpsense commit "2bcd5fe14182378e03092e973e64d2c7e73c4e10"
	- commented out "add_subdirectory(test)" in CMakeLists.txt
- fast_gicp commit "ee1fdbae7dd86284b52a06141358c89982d67850"
- PCL: Version 1.10.0 installed via apt (maybe by installing ROS?) to folder /lib/x86_64-linux-gnu/

**Comment by sumanthrao1997** [comment]
Thank you @aock for the detailed reply. That was the issue with two pcl libraries,  I uninstalled the locally installed one and it works. Thank you for the amazing support

**Comment by sumanthrao1997** [comment]
also @aock and @juliangaal  there is no need to git check out different commits. it works with fast_gicp latest commit and warpsense latest commit as well.

**Comment by juliangaal** [comment]
Sounds great. We should update the docs to mention the PCL conflicts.

Actually, using `find_package(PCL REQUIRED 1.10.0 EXACT)` is probably the best solution
