### ISSUE TITLE
FASTGICP throws std::invalid_argument

### ISSUE THREAD

**Issue by sumanthrao1997** [juliangaal/warpsense#2]
Hello,
I have tried your repo on multiple bag files and the featsense program crashes with this issue on both with os64 and os128 Lidars, could you please elaborate and provide some instructions on what may be causing this issue?

terminate called after throwing an instance of 'std::invalid_argument'
  what():  FastGICP: destination cloud cannot be identical to source or target

**Comment by sumanthrao1997** [comment]
I fixed this by using a previous version of fastgicp

**Comment by juliangaal** [comment]
Please describe the exact versions you have used, thank you.

**Comment by sumanthrao1997** [comment]
In the previous issue #1 , the commit you mentioned works, i.e 
```
cd fast_gicp
git checkout ee1fdbae7dd86284b52a06141358c89982d67850
<compile with CUDA enabled>
```
